texts_dirs:
  root: /mnt/tsukuyomi/sensho/CelebV-Text/texts/
  details: face40_details_new/
  additional:
    action: action_dur/
    emotion: emotion/
    light_direction: light_dir/
    light_intensity: light_intensity/
    light_temp: light_color_temp/

videos_dirs:
  root: /mnt/tsukuyomi/sensho/CelebV-Text/videos/
  untar: celebvtext_6/

seq_len: 5
fps: 30

clip_model: ViT-B/32

log_level: INFO